import requests

class LasairClient:
    """
    A custom API client for the Rubin Observatory / Lasair Alert Broker.
    
    This client replaces the official 'lasair' Python package (v0.1.2) due to 
    authentication issues caused by the library's forced use of HTTP POST 
    requests. This custom implementation uses HTTP GET requests to ensure 
    compatibility with the Lasair REST API endpoints.

    Attributes:
        token (str): The Lasair API access token.
        base_url (str): The base URL for the Lasair API (default: https://lasair.lsst.ac.uk/api).
    """

    def __init__(self, token, base_url="https://lasair.lsst.ac.uk/api"):
        self.token = token
        self.base_url = base_url.rstrip('/')
        self.headers = {'Authorization': f'Token {self.token}'}
        
    def query(self, selected, tables, conditions, limit=1000, offset=0):
        """
        Runs a SQL-like query on the Lasair database.
        
        Args:
            selected (str): The columns to return (e.g., "objectId, ra, dec").
            tables (str): The table to query (usually "objects").
            conditions (str): The WHERE clause (e.g., "magpsf < 18 AND nethist > 10").
            
        Returns:
            list: List of dictionaries containing the query results.
        """
        endpoint = f"{self.base_url}/query/"
        data = {
            'selected': selected,
            'tables': tables,
            'conditions': conditions,
            'limit': limit,
            'offset': offset
        }
        return self._make_request("POST", endpoint, data=data)
    
    def get_object(self, object_id: str, lasair_added: bool = True):
        """
        Retrieves detailed metadata and classification for a specific object.

        This method queries the '/object/' endpoint. It returns the latest 
        known state of the object, including Sherlock classifications and 
        cross-matches with other astronomical catalogs (like TNS or Pan-STARRS).

        Args:
            object_id (str): The unique identifier for the object (e.g., 'ZTF...' or 'DIA...').
            lasair_added (bool): If True, includes extra metadata generated by Lasair, 
                                 such as 'Sherlock' classification and spatial cross-matches.

        Returns:
            dict: A comprehensive dictionary containing positional data (RA/Dec), 
                  discovery stats, and classification labels.
        
        Note:
            Uses a POST request to handle object identifiers and flags securely within the body.
        """
        endpoint = f"{self.base_url}/object/"
        data = {
            'objectId': object_id,
            'lasair_added': 1 if lasair_added else 0, # Viele APIs bevorzugen 1/0 für Booleans
        }
        return self._make_request("POST", endpoint, data=data)

    def _make_request(self, method, url, params=None, data=None):
        """Internal helper to handle requests and errors."""
        try:
            if method == "GET":
                response = requests.get(url, params=params, headers=self.headers, timeout=30)
            else:
                # Bei POST senden wir die Daten als Form-Data, wie von Lasair erwartet
                response = requests.post(url, data=data, headers=self.headers, timeout=600)
            
            if response.status_code == 200:
                return response.json()
            elif response.status_code == 401:
                raise Exception("Unauthorized: Check your API token.")
            else:
                raise Exception(f"API Error {response.status_code}: {response.text}")
        except requests.exceptions.RequestException as e:
            raise Exception(f"Connection Error: {e}")